DELIMITER $$

DROP PROCEDURE IF EXISTS empresa.sp_triggers;

CREATE PROCEDURE IF NOT EXISTS empresa.sp_triggers()
BEGIN
    DELETE FROM facturacion;
    INSERT INTO facturacion
    SELECT A.FECHA, SUM(B.CANTIDAD * B.PRECIO) AS VENTA_TOTAL
    FROM facturas A
    INNER JOIN
    items B
    ON A.NUMERO = B.NUMERO
    GROUP BY A.FECHA;
END $$
DELIMITER ;